services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/dinopoll}
    restart: always
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinopoll
    volumes:
      - "db_volume:/var/lib/postgresql/data"
volumes:
  db_volume:
